{{- if .Values.l1_validator_pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "l1-validator.fullname" . }}
  labels:
    {{- include "l1-validator.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.l1_validator_pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "l1-validator.selectorLabels" . | nindent 6 }}
{{- end }}
