apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: avalanche

resources:
  - ../../base
  - validators.yaml
  - rpc.yaml

commonLabels:
  network: fuji

configMapGenerator:
  - name: avalanche-network
    literals:
      - NETWORK_ID=5
      - NETWORK_NAME=fuji
