---
# Handlers for Safe services

- name: Restart safe services
  ansible.builtin.systemd:
    name: safe
    state: restarted
    daemon_reload: true

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
