{
 "title": "Primary Network",
 "tags": [
  "primary-network",
  "avalanche"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "P-Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "P-Chain Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance) (avalanche_snowman_last_accepted_height{job=~\"primary-network-.*\",chain=\"P\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "P-Chain Poll Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  max by (instance) (\n    increase(avalanche_snowman_polls_successful{job=~\"primary-network-.*\",chain=\"P\"}[5m])\n  )\n  /\n  (\n    max by (instance) (\n      increase(avalanche_snowman_polls_successful{job=~\"primary-network-.*\",chain=\"P\"}[5m])\n    )\n    +\n    max by (instance) (\n      increase(avalanche_snowman_polls_failed{job=~\"primary-network-.*\",chain=\"P\"}[5m])\n    )\n  )\n) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "P-Chain Benched Stake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance) (avalanche_benchlist_benched_weight{job=~\"primary-network-.*\",chain=\"P\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "C-Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "C-Chain Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance) (avalanche_snowman_last_accepted_height{job=~\"primary-network-.*\",chain=\"C\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "C-Chain TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance) (\n  rate(avalanche_coreth_chain_txs_processed{job=~\"primary-network-.*\"}[5m])\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "C-Chain Gas Per Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (instance) (\n  increase(\n    avalanche_coreth_block_gas_used_processed{job=~\"primary-network-.*\"}[5m]\n  )\n)/avg by (instance) (\n  increase(\n    avalanche_coreth_block_inserts_count{job=~\"primary-network-.*\"}[5m]\n  )\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (instance) (go_memstats_alloc_bytes{job=~\"primary-network-.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance) (go_goroutines{job=~\"primary-network-.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance) (avalanche_network_peers{job=~\"primary-network-.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}