apiVersion: v1
kind: Service
metadata:
  name: {{ include "graph-node.fullname" . }}
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.graphqlPort }}
      targetPort: graphql
      protocol: TCP
      name: graphql
    - port: {{ .Values.service.wsPort }}
      targetPort: ws
      protocol: TCP
      name: ws
    - port: {{ .Values.service.statusPort }}
      targetPort: status
      protocol: TCP
      name: status
  selector:
    {{- include "graph-node.selectorLabels" . | nindent 4 }}
