{{- if .Values.ipfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "graph-node.fullname" . }}-ipfs
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.ipfs.storageClass }}
  storageClassName: {{ .Values.ipfs.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.ipfs.storage }}
{{- end }}
