{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "graph-node.fullname" . }}-postgres
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "graph-node.postgres.selectorLabels" . | nindent 4 }}
{{- end }}
