apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graph-node.fullname" . }}
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres_pass: {{ required "postgres.password is required" .Values.postgres.password | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
