output "validator_ips" {
  description = "Public IPs of validator nodes"
  value       = aws_instance.validators[*].public_ip
}

output "validator_private_ips" {
  description = "Private IPs of validator nodes"
  value       = aws_instance.validators[*].private_ip
}

output "rpc_ips" {
  description = "Public IPs of RPC nodes"
  value       = aws_instance.rpc[*].public_ip
}

output "rpc_private_ips" {
  description = "Private IPs of RPC nodes"
  value       = aws_instance.rpc[*].private_ip
}

output "grafana_url" {
  description = "Grafana dashboard URL"
  value       = "http://${aws_instance.validators[0].public_ip}:3000"
}

output "blockscout_url" {
  description = "Blockscout block explorer URL (on RPC node)"
  value       = length(aws_instance.rpc) > 0 ? "http://${aws_instance.rpc[0].public_ip}:4001" : ""
}

output "monitoring_ip" {
  description = "IP of the monitoring node (Grafana, Blockscout)"
  value       = aws_instance.validators[0].public_ip
}

output "vpc_id" {
  description = "VPC ID"
  value       = aws_vpc.main.id
}

output "ansible_inventory" {
  description = "Ansible inventory content"
  value       = <<-EOT
[validators]
%{for i, ip in aws_instance.validators[*].public_ip~}
validator-${i + 1} ansible_host=${ip} ansible_user=ubuntu node_type=validator
%{endfor~}

[rpc]
%{for i, ip in aws_instance.rpc[*].public_ip~}
rpc-${i + 1} ansible_host=${ip} ansible_user=ubuntu node_type=rpc
%{endfor~}

[monitoring]
validator-1 ansible_host=${aws_instance.validators[0].public_ip} ansible_user=ubuntu

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
%{if var.ssh_private_key_file != ""~}
ansible_ssh_private_key_file=${var.ssh_private_key_file}
%{endif~}
EOT
}

# Write inventory file for Ansible
resource "local_file" "ansible_inventory" {
  content  = <<-EOT
[validators]
%{for i, ip in aws_instance.validators[*].public_ip~}
validator-${i + 1} ansible_host=${ip} ansible_user=ubuntu node_type=validator
%{endfor~}

[rpc]
%{for i, ip in aws_instance.rpc[*].public_ip~}
rpc-${i + 1} ansible_host=${ip} ansible_user=ubuntu node_type=rpc
%{endfor~}

[monitoring]
validator-1 ansible_host=${aws_instance.validators[0].public_ip} ansible_user=ubuntu

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
%{if var.ssh_private_key_file != ""~}
ansible_ssh_private_key_file=${var.ssh_private_key_file}
%{endif~}
EOT
  filename = "${path.module}/../../ansible/inventory/aws_hosts"
}

# Write env file for create-l1 tool
resource "local_file" "env_file" {
  content  = <<-EOT
# Generated by Terraform
NETWORK=${var.environment}
%{for i, ip in aws_instance.validators[*].public_ip~}
VALIDATOR_${i + 1}_IP=${ip}
%{endfor~}
%{for i, ip in aws_instance.rpc[*].public_ip~}
RPC_${i + 1}_IP=${ip}
%{endfor~}
EOT
  filename = "${path.module}/../../.env"
}
