apiVersion: v1
kind: Service
metadata:
  name: {{ include "safe.fullname" . }}-cgw
  labels:
    {{- include "safe.cgw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "safe.cgw.selectorLabels" . | nindent 4 }}
