apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "safe.fullname" . }}-cgw
  labels:
    {{- include "safe.cgw.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cgw.replicas }}
  selector:
    matchLabels:
      {{- include "safe.cgw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "safe.cgw.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-cgw.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cgw
          image: "{{ .Values.cgw.image.repository }}:{{ .Values.cgw.image.tag }}"
          imagePullPolicy: {{ .Values.cgw.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "safe.fullname" . }}-cgw
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "safe.fullname" . }}
                  key: postgres-cgw-password
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "safe.fullname" . }}
                  key: webhook-token
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "safe.fullname" . }}
                  key: webhook-token
          livenessProbe:
            httpGet:
              path: /about
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /about
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.cgw.resources | nindent 12 }}
