apiVersion: v1
kind: Service
metadata:
  name: {{ include "safe.fullname" . }}-postgres-cgw
  labels:
    {{- include "safe.postgresCgw.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "safe.postgresCgw.selectorLabels" . | nindent 4 }}
