apiVersion: v1
kind: Service
metadata:
  name: {{ include "safe.fullname" . }}-txs
  labels:
    {{- include "safe.txs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "safe.txs.selectorLabels" . | nindent 4 }}
