apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "safe.fullname" . }}-txs
  labels:
    {{- include "safe.txs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.txs.replicas }}
  selector:
    matchLabels:
      {{- include "safe.txs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "safe.txs.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-txs.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: txs-patches
          configMap:
            name: {{ include "safe.fullname" . }}-txs-patches
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: txs
          image: "{{ .Values.txs.image.repository }}:{{ .Values.txs.image.tag }}"
          imagePullPolicy: {{ .Values.txs.image.pullPolicy }}
          command:
            - docker/web/run_web.sh
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "safe.fullname" . }}-txs
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "safe.fullname" . }}
                  key: txs-secret-key
          livenessProbe:
            httpGet:
              path: /api/v1/about/
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /api/v1/about/
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.txs.resources | nindent 12 }}
          volumeMounts:
            - name: txs-patches
              mountPath: /app/safe_transaction_service/history/indexers/safe_events_indexer.py
              subPath: safe_events_indexer.py
              readOnly: true
