apiVersion: v2
name: l1-validator
description: Avalanche L1 Validator Nodes (Subnet-EVM with Partial Sync)
type: application
version: 0.3.0
appVersion: "1.14.1-v0.8.0"

keywords:
  - avalanche
  - blockchain
  - validator
  - l1
  - subnet
  - subnet-evm
  - partial-sync

home: https://github.com/ava-labs/avalanche-deploy
sources:
  - https://github.com/ava-labs/avalanchego
  - https://github.com/ava-labs/subnet-evm

maintainers:
  - name: Ava Labs
    url: https://avax.network
