apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icm-relayer.fullname" . }}-config
  labels:
    {{- include "icm-relayer.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {
      "log-level": "{{ .Values.logLevel }}",
      "p-chain-api": {
        "base-url": "{{ include "icm-relayer.avalanchegoUrl" . }}"
      },
      "info-api": {
        "base-url": "{{ include "icm-relayer.avalanchegoUrl" . }}"
      },
      "storage-location": "/data/icm-relayer-storage",
      "process-missed-blocks": {{ .Values.processMissedBlocks }},
      "api-port": {{ .Values.ports.api }},
      "metrics-port": {{ .Values.ports.metrics }},
      "source-blockchains": [
        {
          "subnet-id": "{{ .Values.l1.subnetId }}",
          "blockchain-id": "{{ .Values.l1.blockchainId }}",
          "vm": "evm",
          "rpc-endpoint": {
            "base-url": "{{ include "icm-relayer.avalanchegoUrl" . }}/ext/bc/{{ .Values.l1.blockchainId }}/rpc"
          },
          "ws-endpoint": {
            "base-url": "{{ include "icm-relayer.avalanchegoWsUrl" . }}/ext/bc/{{ .Values.l1.blockchainId }}/ws"
          },
          "message-contracts": {
            "0x0000000000000000000000000000000000000000": {
              "message-format": "off-chain-registry"
            }
          }
        }
        {{- if .Values.bidirectional }}
        ,{
          "subnet-id": "{{ include "icm-relayer.cchainSubnetId" . }}",
          "blockchain-id": "{{ include "icm-relayer.cchainBlockchainId" . }}",
          "vm": "evm",
          "rpc-endpoint": {
            "base-url": "{{ include "icm-relayer.avalanchegoUrl" . }}/ext/bc/C/rpc"
          },
          "ws-endpoint": {
            "base-url": "{{ include "icm-relayer.avalanchegoWsUrl" . }}/ext/bc/C/ws"
          },
          "message-contracts": {
            "0x0000000000000000000000000000000000000000": {
              "message-format": "off-chain-registry"
            }
          }
        }
        {{- end }}
      ],
      "destination-blockchains": [
        {
          "subnet-id": "{{ include "icm-relayer.cchainSubnetId" . }}",
          "blockchain-id": "{{ include "icm-relayer.cchainBlockchainId" . }}",
          "vm": "evm",
          "rpc-endpoint": {
            "base-url": "{{ include "icm-relayer.avalanchegoUrl" . }}/ext/bc/C/rpc"
          },
          "account-private-key": "{{ .Values.relayerPrivateKey }}"
        },
        {
          "subnet-id": "{{ .Values.l1.subnetId }}",
          "blockchain-id": "{{ .Values.l1.blockchainId }}",
          "vm": "evm",
          "rpc-endpoint": {
            "base-url": "{{ include "icm-relayer.avalanchegoUrl" . }}/ext/bc/{{ .Values.l1.blockchainId }}/rpc"
          },
          "account-private-key": "{{ .Values.relayerPrivateKey }}"
        }
      ]
    }
