apiVersion: v1
kind: Service
metadata:
  name: {{ include "icm-relayer.fullname" . }}
  labels:
    {{- include "icm-relayer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "icm-relayer.selectorLabels" . | nindent 4 }}
