output "validator_ips" {
  description = "Public IPs of validator nodes"
  value       = azurerm_public_ip.validators[*].ip_address
}

output "validator_private_ips" {
  description = "Private IPs of validator nodes"
  value       = azurerm_network_interface.validators[*].private_ip_address
}

output "rpc_ips" {
  description = "Public IPs of RPC nodes"
  value       = azurerm_public_ip.rpc[*].ip_address
}

output "rpc_private_ips" {
  description = "Private IPs of RPC nodes"
  value       = azurerm_network_interface.rpc[*].private_ip_address
}

output "grafana_url" {
  description = "Grafana dashboard URL"
  value       = "http://${azurerm_public_ip.validators[0].ip_address}:3000"
}

output "blockscout_url" {
  description = "Blockscout block explorer URL"
  value       = "http://${azurerm_public_ip.validators[0].ip_address}:4001"
}

output "monitoring_ip" {
  description = "IP of the monitoring node (Grafana, Blockscout)"
  value       = azurerm_public_ip.validators[0].ip_address
}

output "resource_group_name" {
  description = "Resource group name"
  value       = azurerm_resource_group.main.name
}

output "ansible_inventory" {
  description = "Ansible inventory content"
  value       = <<-EOT
[validators]
%{for i, ip in azurerm_public_ip.validators[*].ip_address~}
validator-${i + 1} ansible_host=${ip} ansible_user=${var.admin_username}
%{endfor~}

[rpc]
%{for i, ip in azurerm_public_ip.rpc[*].ip_address~}
rpc-${i + 1} ansible_host=${ip} ansible_user=${var.admin_username}
%{endfor~}

[monitoring]
validator-1 ansible_host=${azurerm_public_ip.validators[0].ip_address} ansible_user=${var.admin_username}

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOT
}

resource "local_file" "ansible_inventory" {
  content  = <<-EOT
[validators]
%{for i, ip in azurerm_public_ip.validators[*].ip_address~}
validator-${i + 1} ansible_host=${ip} ansible_user=${var.admin_username}
%{endfor~}

[rpc]
%{for i, ip in azurerm_public_ip.rpc[*].ip_address~}
rpc-${i + 1} ansible_host=${ip} ansible_user=${var.admin_username}
%{endfor~}

[monitoring]
validator-1 ansible_host=${azurerm_public_ip.validators[0].ip_address} ansible_user=${var.admin_username}

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOT
  filename = "${path.module}/../../ansible/inventory/azure_hosts"
}

resource "local_file" "env_file" {
  content  = <<-EOT
# Generated by Terraform
NETWORK=${var.environment}
%{for i, ip in azurerm_public_ip.validators[*].ip_address~}
VALIDATOR_${i + 1}_IP=${ip}
%{endfor~}
%{for i, ip in azurerm_public_ip.rpc[*].ip_address~}
RPC_${i + 1}_IP=${ip}
%{endfor~}
EOT
  filename = "${path.module}/../../.env"
}
