{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockscout.fullname" . }}-postgres
  labels:
    {{- include "blockscout.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "blockscout.postgresSelectorLabels" . | nindent 4 }}
{{- end }}
