apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout.fullname" . }}
  labels:
    {{- include "blockscout.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ include "blockscout.databasePassword" . | quote }}
  secret-key-base: {{ include "blockscout.secretKeyBase" . | quote }}
