apiVersion: v1
kind: Secret
metadata:
  name: {{ include "faucet.fullname" . }}
  labels:
    {{- include "faucet.labels" . | nindent 4 }}
type: Opaque
stringData:
  PRIVATE_KEY: {{ .Values.faucet.privateKey | quote }}
