{{- if .Values.primary_validator_serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "primary-network-validator.serviceAccountName" . }}
  labels:
    {{- include "primary-network-validator.labels" . | nindent 4 }}
{{- end }}
