{{- if .Values.l1_rpc_serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "l1-rpc.serviceAccountName" . }}
  labels:
    {{- include "l1-rpc.labels" . | nindent 4 }}
{{- end }}
