apiVersion: v1
kind: Service
metadata:
  name: {{ include "l1-rpc.fullname" . }}
  labels:
    {{- include "l1-rpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.l1_rpc_service.type }}
  ports:
    - port: {{ .Values.l1_rpc_service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.l1_rpc_service.stakingPort }}
      targetPort: staking
      protocol: TCP
      name: staking
  selector:
    {{- include "l1-rpc.selectorLabels" . | nindent 4 }}
