apiVersion: v1
kind: Service
metadata:
  name: {{ include "avalanche-rpc.fullname" . }}
  labels:
    {{- include "avalanche-rpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.stakingPort }}
      targetPort: staking
      protocol: TCP
      name: staking
  selector:
    {{- include "avalanche-rpc.selectorLabels" . | nindent 4 }}
