output "validator_ips" {
  description = "Public IPs of validator nodes"
  value       = google_compute_instance.validators[*].network_interface[0].access_config[0].nat_ip
}

output "validator_private_ips" {
  description = "Private IPs of validator nodes"
  value       = google_compute_instance.validators[*].network_interface[0].network_ip
}

output "rpc_ips" {
  description = "Public IPs of RPC nodes"
  value       = google_compute_instance.rpc[*].network_interface[0].access_config[0].nat_ip
}

output "rpc_private_ips" {
  description = "Private IPs of RPC nodes"
  value       = google_compute_instance.rpc[*].network_interface[0].network_ip
}

output "grafana_url" {
  description = "Grafana dashboard URL"
  value       = "http://${google_compute_instance.monitoring.network_interface[0].access_config[0].nat_ip}:3000"
}

output "blockscout_url" {
  description = "Blockscout block explorer URL (on RPC node)"
  value       = length(google_compute_instance.rpc) > 0 ? "http://${google_compute_instance.rpc[0].network_interface[0].access_config[0].nat_ip}:4001" : ""
}

output "monitoring_ip" {
  description = "IP of the dedicated monitoring server (Prometheus, Grafana)"
  value       = google_compute_instance.monitoring.network_interface[0].access_config[0].nat_ip
}

output "monitoring_private_ip" {
  description = "Private IP of the monitoring server"
  value       = google_compute_instance.monitoring.network_interface[0].network_ip
}

output "ansible_inventory" {
  description = "Ansible inventory content"
  value       = <<-EOT
[validators]
%{for i, instance in google_compute_instance.validators~}
validator-${i + 1} ansible_host=${instance.network_interface[0].access_config[0].nat_ip} ansible_user=${var.ssh_user} node_type=validator
%{endfor~}

[rpc]
%{for i, instance in google_compute_instance.rpc~}
rpc-${i + 1} ansible_host=${instance.network_interface[0].access_config[0].nat_ip} ansible_user=${var.ssh_user} node_type=rpc
%{endfor~}

[monitoring]
monitoring-1 ansible_host=${google_compute_instance.monitoring.network_interface[0].access_config[0].nat_ip} ansible_user=${var.ssh_user}

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOT
}

resource "local_file" "ansible_inventory" {
  content  = <<-EOT
[validators]
%{for i, instance in google_compute_instance.validators~}
validator-${i + 1} ansible_host=${instance.network_interface[0].access_config[0].nat_ip} ansible_user=${var.ssh_user} node_type=validator
%{endfor~}

[rpc]
%{for i, instance in google_compute_instance.rpc~}
rpc-${i + 1} ansible_host=${instance.network_interface[0].access_config[0].nat_ip} ansible_user=${var.ssh_user} node_type=rpc
%{endfor~}

[monitoring]
monitoring-1 ansible_host=${google_compute_instance.monitoring.network_interface[0].access_config[0].nat_ip} ansible_user=${var.ssh_user}

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOT
  filename = "${path.module}/../../ansible/inventory/gcp_hosts"
}

resource "local_file" "env_file" {
  content  = <<-EOT
# Generated by Terraform
NETWORK=${var.environment}
%{for i, instance in google_compute_instance.validators~}
VALIDATOR_${i + 1}_IP=${instance.network_interface[0].access_config[0].nat_ip}
%{endfor~}
%{for i, instance in google_compute_instance.rpc~}
RPC_${i + 1}_IP=${instance.network_interface[0].access_config[0].nat_ip}
%{endfor~}
EOT
  filename = "${path.module}/../../.env"
}
