{{/* Chart naming and labels. */}}
{{- define "relayerd.name" -}}
{{- default "relayer" .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "relayerd.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := include "relayerd.name" . -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end }}

{{- define "relayerd.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "relayerd.selectorLabels" -}}
app.kubernetes.io/name: relayer
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{- define "relayerd.labels" -}}
helm.sh/chart: {{ include "relayerd.chart" . }}
{{ include "relayerd.selectorLabels" . }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/component: relayer
{{- end }}

{{- define "relayerd.serviceAccountName" -}}
{{- if .Values.serviceAccount.create -}}
{{- default (include "relayerd.fullname" .) .Values.serviceAccount.name -}}
{{- else -}}
{{- default "default" .Values.serviceAccount.name -}}
{{- end -}}
{{- end }}

{{- define "relayerd.runtimeSecretName" -}}
{{- required "runtimeSecret.name is required and must name the Secret generated by relayer-setup" .Values.runtimeSecret.name -}}
{{- end }}

{{- define "relayerd.runtimeSecretChecksum" -}}
{{- $name := include "relayerd.runtimeSecretName" . -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $name -}}
{{- if $secret -}}
{{- toJson (default dict $secret.data) | sha256sum -}}
{{- else -}}
{{- printf "unresolved:%s" $name | sha256sum -}}
{{- end -}}
{{- end }}

{{- define "relayerd.avalanchegoUrl" -}}
http://{{ required "avalanchego.serviceName is required" .Values.avalanchego.serviceName }}:{{ .Values.avalanchego.httpPort }}
{{- end }}

{{- define "relayerd.evmRpcUrl" -}}
{{ include "relayerd.avalanchegoUrl" . }}/ext/bc/{{ .Values.l1.blockchainId }}/rpc
{{- end }}

{{- define "relayerd.networkId" -}}
{{- if eq .Values.network "mainnet" -}}1
{{- else if eq .Values.network "fuji" -}}5
{{- else -}}{{ fail (printf "network must be fuji or mainnet, got %q" .Values.network) }}
{{- end -}}
{{- end }}

{{/* Fail at render time instead of installing an unsafe or incomplete workload. */}}
{{- define "relayerd.validate" -}}
{{- if ne (int .Values.replicas) 1 -}}
{{- fail "replicas must be exactly 1: relayerd and the console are single-instance workloads" -}}
{{- end -}}
{{- if and (ne .Values.network "fuji") (ne .Values.network "mainnet") -}}
{{- fail (printf "network must be fuji or mainnet, got %q" .Values.network) -}}
{{- end -}}
{{- if not .Values.l1.subnetId -}}{{ fail "l1.subnetId is required" -}}{{- end -}}
{{- if not .Values.l1.blockchainId -}}{{ fail "l1.blockchainId is required" -}}{{- end -}}
{{- if le (int64 .Values.l1.evmChainId) 0 -}}{{ fail "l1.evmChainId must be a positive integer" -}}{{- end -}}
{{- if not .Values.l1.chainName -}}{{ fail "l1.chainName is required" -}}{{- end -}}
{{- if not .Values.l1.managerAddress -}}{{ fail "l1.managerAddress (the PoAManager) is required" -}}{{- end -}}
{{- if not .Values.l1.validatorManagerAddress -}}{{ fail "l1.validatorManagerAddress (the ValidatorManager proxy) is required" -}}{{- end -}}
{{- if not (regexMatch "^0x[0-9a-fA-F]{40}$" .Values.l1.managerAddress) -}}{{ fail "l1.managerAddress must be a 20-byte hex EVM address" -}}{{- end -}}
{{- if not (regexMatch "^0x[0-9a-fA-F]{40}$" .Values.l1.validatorManagerAddress) -}}{{ fail "l1.validatorManagerAddress must be a 20-byte hex EVM address" -}}{{- end -}}
{{- if eq (lower .Values.l1.managerAddress) (lower .Values.l1.validatorManagerAddress) -}}
{{- fail "l1.managerAddress and l1.validatorManagerAddress must differ for the supported PoAManager topology" -}}
{{- end -}}
{{- if not .Values.operatorIdentity -}}{{ fail "operatorIdentity is required for the namespace-scoped port-forward RoleBinding" -}}{{- end -}}
{{- if not .Values.runtimeSecret.name -}}{{ fail "runtimeSecret.name is required; the chart never creates or owns key material" -}}{{- end -}}
{{- if not (regexMatch "^.+@sha256:[0-9a-f]{64}$" .Values.images.relayerd.reference) -}}{{ fail "images.relayerd.reference must be an immutable sha256 digest" -}}{{- end -}}
{{- if not (regexMatch "^.+@sha256:[0-9a-f]{64}$" .Values.images.console.reference) -}}{{ fail "images.console.reference must be an immutable sha256 digest" -}}{{- end -}}
{{- if not (regexMatch "^.+@sha256:[0-9a-f]{64}$" .Values.images.init.reference) -}}{{ fail "images.init.reference must be an immutable sha256 digest" -}}{{- end -}}
{{- if eq (len .Values.networkPolicy.dns.podSelector) 0 -}}{{ fail "networkPolicy.dns.podSelector must not be empty" -}}{{- end -}}
{{- if eq (len .Values.networkPolicy.rpc.podSelector) 0 -}}{{ fail "networkPolicy.rpc.podSelector must not be empty" -}}{{- end -}}
{{- if eq (len .Values.networkPolicy.validators.podSelector) 0 -}}{{ fail "networkPolicy.validators.podSelector must not be empty" -}}{{- end -}}
{{- if le (int .Values.avalanchego.httpPort) 0 -}}{{ fail "avalanchego.httpPort must be positive" -}}{{- end -}}
{{- if le (int .Values.networkPolicy.validators.p2pPort) 0 -}}{{ fail "networkPolicy.validators.p2pPort must be positive" -}}{{- end -}}
{{- if and .Values.stateBackup.enabled (le (int .Values.stateBackup.intervalSeconds) 0) -}}{{ fail "stateBackup.intervalSeconds must be positive when backups are enabled" -}}{{- end -}}
{{- if lt (int .Values.terminationGracePeriodSeconds) (add (int .Values.acceptanceTimeoutSeconds) 540) -}}
{{- fail (printf "terminationGracePeriodSeconds must be at least acceptanceTimeoutSeconds + 540 (%d)" (add (int .Values.acceptanceTimeoutSeconds) 540) ) -}}
{{- end -}}
{{- range $index, $peer := .Values.manuallyTrackedPeers -}}
{{- if not $peer.nodeId -}}{{ fail (printf "manuallyTrackedPeers[%d].nodeId is required" $index) -}}{{- end -}}
{{- if not $peer.ip -}}{{ fail (printf "manuallyTrackedPeers[%d].ip is required" $index) -}}{{- end -}}
{{- end -}}
{{- if .Values.safe.enabled -}}
{{- if not .Values.safe.address -}}{{ fail "safe.address is required when safe.enabled=true" -}}{{- end -}}
{{- if not (regexMatch "^0x[0-9a-fA-F]{40}$" .Values.safe.address) -}}{{ fail "safe.address must be a 20-byte hex EVM address" -}}{{- end -}}
{{- if not .Values.safe.transactionServiceUrl -}}{{ fail "safe.transactionServiceUrl is required when safe.enabled=true" -}}{{- end -}}
{{- if eq (len .Values.safe.podSelector) 0 -}}{{ fail "safe.podSelector is required when safe.enabled=true so egress remains restricted" -}}{{- end -}}
{{- if le (int .Values.safe.port) 0 -}}{{ fail "safe.port must be positive when safe.enabled=true" -}}{{- end -}}
{{- end -}}
{{- end }}
