{{- if or (and (eq .Values.storage.provider "s3") .Values.aws.accessKeyId) (and (eq .Values.storage.provider "gcs") .Values.gcs.serviceAccountKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "staking-key-backup.fullname" . }}
  labels:
    {{- include "staking-key-backup.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and (eq .Values.storage.provider "s3") .Values.aws.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if and (eq .Values.storage.provider "gcs") .Values.gcs.serviceAccountKey }}
  gcs-service-account.json: {{ .Values.gcs.serviceAccountKey | quote }}
  {{- end }}
{{- end }}
