{{- if .Values.primary_rpc_serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "primary-network-rpc.serviceAccountName" . }}
  labels:
    {{- include "primary-network-rpc.labels" . | nindent 4 }}
{{- end }}
